---

- name: Install packages
  include_tasks: install.yml
  when: not rclone_skip_install

- name: Install configs
  when: rclone_configs is defined
  become: true
  block:
    - name: Create config directory
      ansible.builtin.file:
        path: '{{ rclone_config_location | dirname }}'
        state: directory
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        mode: '0755'

    - name: Set up rclone config
      ansible.builtin.template:
        src: rclone.conf.j2
        owner: '{{ rclone_config_owner.OWNER }}'
        group: '{{ rclone_config_owner.GROUP }}'
        dest: '{{ rclone_config_location }}'
        mode: 0600
      register: setup_rclone_config
